version: '3.1'

services:

  db:
    image: ${POSTGRES_IMAGE}
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - adventure_works_data:/var/lib/postgresql/data
    networks:
      - database
    ports:
      - 5432:5432

volumes:
  adventure_works_data:
    external: true

networks:
  database:
    external: true
